import { Game } from '../types';

export type ThemeId = 'cyber' | 'mojave' | 'bg3' | 'rdr2' | 'stardew';

export interface GamePresentation {
  game: Game;
  theme: ThemeId;
  code: string;
  shortName: string;
  name: string;
  primaryClass: string;
  secondaryClass: string;
  dangerClass: string;
  primaryBorderClass: string;
  secondaryBorderClass: string;
  primaryBgClass: string;
  secondaryBgClass: string;
  softPrimaryBgClass: string;
  softSecondaryBgClass: string;
  shadowClass: string;
  frameClass: string;
  panelClass: string;
  compactPanelClass: string;
  cardFrameClass: string;
  previewFrameClass: string;
  cardBodyClass: string;
  cardBackClass: string;
  buttonShapeClass: string;
  neutralButtonClass: string;
  rejectButtonClass: string;
  approveButtonClass: string;
  landingPanelClass: string;
  landingAccentClass: string;
  landingBackdropClass: string;
  inputClass: string;
  listItemClass: string;
  progressGradientClass: string;
  scanGridClass: string;
  titleClass: string;
  bodyFontClass: string;
  headerStatus: string;
  bootSystem: string;
  bootTitle: string;
  bootDescription: string;
  bootProgressLabel: string;
  bootStatusFallback: string;
  bootThroughputFallback: string;
  phaseLabels: Record<'auth' | 'pool' | 'fetching' | 'lists' | 'complete', string>;
  currentState: string;
  completeState: string;
  waitingState: string;
  introLabel: string;
  previewState: string;
  nextLabel: string;
  readyLabel: string;
  recallLabel: string;
  loadingTitle: string;
  loadingBody: string;
  loadingSubtext: string;
  emptyTitle: string;
  emptyBody: string;
  emptySubtext: string;
  approveLabel: string;
  rejectLabel: string;
  approveOverlayLabel: string;
  rejectOverlayLabel: string;
  approvedListTitle: string;
  emptyApprovedText: string;
  queueLabel: string;
  introStatus: string;
  refreshStatus: string;
  refreshTitle: string;
  refreshBody: string;
  resetTitle: string;
  resetAction: string;
  exportLabel: string;
  accessLabel: string;
  targetLabel: string;
  startLabel: string;
  startSubLabel: string;
  protocolLabel: string;
  cardBackLeft: string;
  cardBackRight: string;
}

const presentations: Record<Game, GamePresentation> = {
  [Game.CYBERPUNK]: {
    game: Game.CYBERPUNK,
    theme: 'cyber',
    code: 'SMS',
    shortName: 'CP2077',
    name: 'Cyberpunk 2077',
    primaryClass: 'text-cp-yellow',
    secondaryClass: 'text-cp-cyan',
    dangerClass: 'text-cp-red',
    primaryBorderClass: 'border-cp-yellow',
    secondaryBorderClass: 'border-cp-cyan',
    primaryBgClass: 'bg-cp-yellow',
    secondaryBgClass: 'bg-cp-cyan',
    softPrimaryBgClass: 'bg-cp-yellow/10',
    softSecondaryBgClass: 'bg-cp-cyan/10',
    shadowClass: 'shadow-[0_0_42px_rgba(0,229,255,0.1)]',
    frameClass: 'cp-clip-box border-cp-cyan/25 bg-black/82',
    panelClass: 'cp-clip-box border-l-2 border-cp-yellow bg-cp-dark/90 backdrop-blur-sm',
    compactPanelClass: 'cp-clip-box border border-cp-gray bg-cp-dark/80',
    cardFrameClass: 'cp-clip-box border-l-4 border-cp-yellow bg-black shadow-[0_24px_80px_rgba(0,0,0,0.45)]',
    previewFrameClass: 'cp-clip-box border border-cp-cyan/15 bg-black/65 shadow-[0_18px_60px_rgba(0,0,0,0.35)]',
    cardBodyClass: 'bg-cp-dark',
    cardBackClass: 'cp-clip-box border-cp-yellow/45 bg-[linear-gradient(145deg,#141111,#09090d_45%,#08070b)] shadow-[0_20px_60px_rgba(252,238,10,0.14)]',
    buttonShapeClass: 'cp-clip-btn',
    neutralButtonClass: 'cp-clip-btn border-gray-700 bg-black/55 text-gray-400 hover:border-cp-yellow/50 hover:text-cp-yellow',
    rejectButtonClass: 'cp-clip-btn border-cp-red/45 bg-black/60 text-cp-red hover:border-cp-red hover:bg-cp-red/10 hover:text-white',
    approveButtonClass: 'cp-clip-btn border-cp-cyan/45 bg-black/60 text-cp-cyan hover:border-cp-cyan hover:bg-cp-cyan/10 hover:text-white',
    landingPanelClass: 'cp-clip-box border-2 border-cp-yellow border-l-2 bg-cp-dark/90 shadow-[0_0_50px_rgba(252,238,10,0.2)] backdrop-blur-sm',
    landingAccentClass: 'after:absolute after:right-0 after:top-0 after:h-1 after:w-16 after:bg-cp-yellow after:opacity-50',
    landingBackdropClass: '',
    inputClass: 'bg-cp-dark border-gray-700 focus:border-cp-cyan',
    listItemClass: 'border-gray-800 bg-gray-900/50 hover:border-cp-cyan',
    progressGradientClass: 'from-cp-yellow via-cp-cyan to-cp-red',
    scanGridClass: 'cp-boot-grid',
    titleClass: 'uppercase tracking-tighter transform -skew-x-6',
    bodyFontClass: 'font-sans',
    headerStatus: 'NET_STATUS: ONLINE',
    bootSystem: 'Nexus Secure Uplink',
    bootTitle: 'JACKING IN...',
    bootDescription: 'Rebuilding your swipe deck, syncing cache shards, and priming the next batch before you hit the stack.',
    bootProgressLabel: 'Boot Sequence',
    bootStatusFallback: 'Standing by for handshake...',
    bootThroughputFallback: 'Awaiting telemetry',
    phaseLabels: {
      auth: 'Credential Handshake',
      pool: 'Scanning Mod Pool',
      fetching: 'Pulling Mod Packets',
      lists: 'Syncing Curated Feeds',
      complete: 'Deck Primed',
    },
    currentState: 'Live',
    completeState: 'Locked',
    waitingState: 'Standby',
    introLabel: 'DECK PRIMING',
    previewState: 'Buffered',
    nextLabel: 'Next In Queue',
    readyLabel: 'ready',
    recallLabel: 'RECALL CONFIRMED',
    loadingTitle: 'JACKING IN...',
    loadingBody: 'Rebuilding your queue from the Nexus uplink.',
    loadingSubtext: 'Hold tight - fresh cards are being assembled.',
    emptyTitle: 'Queue Depleted',
    emptyBody: 'You have swiped through the current batch.',
    emptySubtext: 'Use the refresh button to build a new stack.',
    approveLabel: 'Approve',
    rejectLabel: 'Reject',
    approveOverlayLabel: 'Install',
    rejectOverlayLabel: 'Skip',
    approvedListTitle: 'APPROVED_MODS_CACHE',
    emptyApprovedText: 'NO DATA FRAGMENTS FOUND. RETURN TO SCANNING.',
    queueLabel: 'buffered',
    introStatus: 'deck priming...',
    refreshStatus: 'refreshing buffer...',
    refreshTitle: 'Buffer Refresh',
    refreshBody: 'Fetching fresh packets from the Nexus uplink.',
    resetTitle: 'Confirm Reset',
    resetAction: 'Reset All',
    exportLabel: 'Export List',
    accessLabel: 'Access Token (Nexus API)',
    targetLabel: 'Target System (Game)',
    startLabel: 'Initialize Connection',
    startSubLabel: 'Establish Uplink',
    protocolLabel: 'Nexus Protocol V.2.0.77',
    cardBackLeft: 'Stack',
    cardBackRight: 'Sync',
  },
  [Game.NEWVEGAS]: {
    game: Game.NEWVEGAS,
    theme: 'mojave',
    code: 'MMS',
    shortName: 'New Vegas',
    name: 'Fallout: New Vegas',
    primaryClass: 'text-[#d9902f]',
    secondaryClass: 'text-[#6bbf59]',
    dangerClass: 'text-[#d45f3d]',
    primaryBorderClass: 'border-[#d9902f]',
    secondaryBorderClass: 'border-[#6bbf59]',
    primaryBgClass: 'bg-[#d9902f]',
    secondaryBgClass: 'bg-[#6bbf59]',
    softPrimaryBgClass: 'bg-[#d9902f]/10',
    softSecondaryBgClass: 'bg-[#6bbf59]/10',
    shadowClass: 'shadow-[0_18px_80px_rgba(217,144,47,0.13)]',
    frameClass: 'rounded-sm border-[#4c3b22] bg-[#0b0905]/88',
    panelClass: 'rounded-sm border border-[#4c3b22] bg-[#0b0905]/92 backdrop-blur-sm',
    compactPanelClass: 'rounded-sm border border-[#4c3b22] bg-[#0b0905]/84',
    cardFrameClass: 'rounded-sm border border-[#4c3b22] border-l-4 border-l-[#d9902f] bg-[#100c07] shadow-[0_24px_70px_rgba(42,25,10,0.55)]',
    previewFrameClass: 'rounded-sm border border-[#6bbf59]/15 bg-[#0b0905]/72 shadow-[0_18px_60px_rgba(107,191,89,0.1)]',
    cardBodyClass: 'bg-[#0c0a06]',
    cardBackClass: 'rounded-sm border-[#d9902f]/45 bg-[linear-gradient(145deg,#221809,#0d0a06_50%,#130d06)] shadow-[0_20px_60px_rgba(217,144,47,0.14)]',
    buttonShapeClass: 'rounded-sm',
    neutralButtonClass: 'rounded-sm border-[#4c3b22] bg-[#0b0905]/72 text-[#9f7a43] hover:border-[#d9902f]/60 hover:text-[#d9902f]',
    rejectButtonClass: 'rounded-sm border-[#8f3d2d]/55 bg-[#130b06]/80 text-[#d45f3d] hover:border-[#d45f3d] hover:bg-[#d45f3d]/10 hover:text-[#ffd0bc]',
    approveButtonClass: 'rounded-sm border-[#6bbf59]/45 bg-[#0b1008]/80 text-[#6bbf59] hover:border-[#6bbf59] hover:bg-[#6bbf59]/10 hover:text-[#d8ffd0]',
    landingPanelClass: 'rounded-sm border-2 border-[#d9902f] bg-[#080704]/92 shadow-[0_18px_80px_rgba(0,0,0,0.55),0_0_45px_rgba(217,144,47,0.12)]',
    landingAccentClass: 'before:absolute before:inset-x-0 before:top-0 before:h-1 before:bg-gradient-to-r before:from-[#4b2e14] before:via-[#d9902f] before:to-[#4b2e14]',
    landingBackdropClass: 'bg-[radial-gradient(circle_at_center,rgba(102,64,24,0.22),transparent_42%),linear-gradient(180deg,#090806,#151009_48%,#070604_100%)]',
    inputClass: 'bg-[#12100a] border-[#4c3b22] focus:border-[#6bbf59]',
    listItemClass: 'border-[#4c3b22] bg-[#100c07]/70 hover:border-[#6bbf59]',
    progressGradientClass: 'from-[#d9902f] via-[#6bbf59] to-[#d45f3d]',
    scanGridClass: 'nv-boot-grid',
    titleClass: 'font-mono uppercase tracking-[-0.02em]',
    bodyFontClass: 'font-mono',
    headerStatus: 'RADIO_STATUS: TUNED',
    bootSystem: 'Mojave Relay Station',
    bootTitle: 'TUNING RADIO...',
    bootDescription: 'Dialing into the Nexus signal, checking the local cache, and dealing a fresh stack for the Mojave run.',
    bootProgressLabel: 'Signal Lock',
    bootStatusFallback: 'Waiting for a clean frequency...',
    bootThroughputFallback: 'Listening for carrier wave',
    phaseLabels: {
      auth: 'Ranger Pass Check',
      pool: 'Sweeping the Mojave Band',
      fetching: 'Recovering Mod Broadcasts',
      lists: 'Checking Caravan Routes',
      complete: 'Hand Dealt',
    },
    currentState: 'On Air',
    completeState: 'Logged',
    waitingState: 'Static',
    introLabel: 'CARAVAN DEALING',
    previewState: 'Queued',
    nextLabel: 'Next Broadcast',
    readyLabel: 'armed',
    recallLabel: 'UNDO LOGGED',
    loadingTitle: 'TUNING RADIO...',
    loadingBody: 'Rebuilding your route from the Nexus relay.',
    loadingSubtext: 'Hold steady - fresh cards are coming over the wire.',
    emptyTitle: 'Trail Cleared',
    emptyBody: 'You have checked every mod in the current hand.',
    emptySubtext: 'Use refresh to tune another Mojave broadcast.',
    approveLabel: 'Keep',
    rejectLabel: 'Pass',
    approveOverlayLabel: 'Keep',
    rejectOverlayLabel: 'Pass',
    approvedListTitle: 'MOJAVE_KEEP_LEDGER',
    emptyApprovedText: 'NO KEEPERS LOGGED. RETURN TO THE TRAIL.',
    queueLabel: 'on frequency',
    introStatus: 'dealing hand...',
    refreshStatus: 'tuning relay...',
    refreshTitle: 'Relay Refresh',
    refreshBody: 'Tuning fresh broadcasts from the Nexus relay.',
    resetTitle: 'Clear Trail Log',
    resetAction: 'Clear All',
    exportLabel: 'Export Ledger',
    accessLabel: 'Courier Passcode (Nexus API)',
    targetLabel: 'Radio Territory (Game)',
    startLabel: 'Start Mojave Run',
    startSubLabel: 'Tune Relay',
    protocolLabel: 'Mojave Uplink V.2281',
    cardBackLeft: 'Deck',
    cardBackRight: 'Trail',
  },
  [Game.BG3]: {
    game: Game.BG3,
    theme: 'bg3',
    code: 'BGS',
    shortName: 'BG3',
    name: "Baldur's Gate 3",
    primaryClass: 'text-[#d8b56d]',
    secondaryClass: 'text-[#b564f7]',
    dangerClass: 'text-[#ff6b5f]',
    primaryBorderClass: 'border-[#d8b56d]',
    secondaryBorderClass: 'border-[#b564f7]',
    primaryBgClass: 'bg-[#d8b56d]',
    secondaryBgClass: 'bg-[#b564f7]',
    softPrimaryBgClass: 'bg-[#d8b56d]/10',
    softSecondaryBgClass: 'bg-[#b564f7]/10',
    shadowClass: 'shadow-[0_22px_90px_rgba(181,100,247,0.16)]',
    frameClass: 'rounded-2xl border-[#6f4a2c] bg-[#160d16]/88',
    panelClass: 'rounded-2xl border border-[#6f4a2c] bg-[#160d16]/90 backdrop-blur-sm',
    compactPanelClass: 'rounded-2xl border border-[#6f4a2c] bg-[#160d16]/82',
    cardFrameClass: 'rounded-2xl border border-[#6f4a2c] border-t-4 border-t-[#d8b56d] bg-[#170d12] shadow-[0_28px_90px_rgba(26,8,32,0.62)]',
    previewFrameClass: 'rounded-2xl border border-[#b564f7]/20 bg-[#170d20]/72 shadow-[0_20px_70px_rgba(181,100,247,0.13)]',
    cardBodyClass: 'bg-[linear-gradient(180deg,#201421,#110b12)]',
    cardBackClass: 'rounded-2xl border-[#d8b56d]/40 bg-[radial-gradient(circle_at_top,rgba(181,100,247,0.18),transparent_46%),linear-gradient(145deg,#211226,#100a13)] shadow-[0_20px_70px_rgba(181,100,247,0.16)]',
    buttonShapeClass: 'rounded-xl',
    neutralButtonClass: 'rounded-xl border-[#6f4a2c] bg-[#140d12]/75 text-[#9f855b] hover:border-[#d8b56d]/70 hover:text-[#d8b56d]',
    rejectButtonClass: 'rounded-xl border-[#933d39]/55 bg-[#1b0d12]/80 text-[#ff6b5f] hover:border-[#ff6b5f] hover:bg-[#ff6b5f]/10 hover:text-[#ffe0dc]',
    approveButtonClass: 'rounded-xl border-[#b564f7]/45 bg-[#170d24]/80 text-[#c992ff] hover:border-[#b564f7] hover:bg-[#b564f7]/12 hover:text-white',
    landingPanelClass: 'rounded-2xl border border-[#d8b56d]/70 bg-[#160d16]/92 shadow-[0_26px_90px_rgba(181,100,247,0.16)]',
    landingAccentClass: 'before:absolute before:inset-x-8 before:top-0 before:h-px before:bg-gradient-to-r before:from-transparent before:via-[#d8b56d] before:to-transparent',
    landingBackdropClass: 'bg-[radial-gradient(circle_at_top,rgba(181,100,247,0.18),transparent_36%),radial-gradient(circle_at_bottom_left,rgba(216,181,109,0.12),transparent_28%),linear-gradient(180deg,#0b0810,#1b0f17_55%,#070508)]',
    inputClass: 'bg-[#110a12] border-[#6f4a2c] focus:border-[#b564f7]',
    listItemClass: 'border-[#6f4a2c] bg-[#170d12]/70 hover:border-[#b564f7]',
    progressGradientClass: 'from-[#d8b56d] via-[#b564f7] to-[#ff6b5f]',
    scanGridClass: 'bg3-boot-grid',
    titleClass: 'font-serif normal-case tracking-normal',
    bodyFontClass: 'font-serif',
    headerStatus: 'CAMP_STATUS: GATHERED',
    bootSystem: 'Astral Archive',
    bootTitle: 'Opening the Grimoire',
    bootDescription: 'Consulting the Nexus ledger, scribing a fresh party of mods, and binding the next choices into your camp journal.',
    bootProgressLabel: 'Ritual Circle',
    bootStatusFallback: 'The ink is waking...',
    bootThroughputFallback: 'Awaiting arcane notation',
    phaseLabels: {
      auth: 'Sigil Recognition',
      pool: 'Reading the Archive',
      fetching: 'Scribing Mod Pages',
      lists: 'Consulting Tavern Boards',
      complete: 'Grimoire Bound',
    },
    currentState: 'Channeling',
    completeState: 'Sealed',
    waitingState: 'Dormant',
    introLabel: 'PAGES TURNING',
    previewState: 'Bookmarked',
    nextLabel: 'Next Page',
    readyLabel: 'prepared',
    recallLabel: 'FATE REWOUND',
    loadingTitle: 'Opening the Grimoire',
    loadingBody: 'Scribing a fresh mod party from the Nexus archive.',
    loadingSubtext: 'The circle is not complete yet.',
    emptyTitle: 'Chapter Finished',
    emptyBody: 'This volume of mods has been judged.',
    emptySubtext: 'Refresh to open another tome.',
    approveLabel: 'Bind',
    rejectLabel: 'Banish',
    approveOverlayLabel: 'Bind',
    rejectOverlayLabel: 'Banish',
    approvedListTitle: 'BOUND_PARTY_MODS',
    emptyApprovedText: 'NO SPELLS BOUND TO THE JOURNAL.',
    queueLabel: 'pages marked',
    introStatus: 'turning pages...',
    refreshStatus: 'consulting archive...',
    refreshTitle: 'Archive Refresh',
    refreshBody: 'Scribing additional pages from Nexus.',
    resetTitle: 'Burn Journal',
    resetAction: 'Burn All',
    exportLabel: 'Export Journal',
    accessLabel: 'Arcane Key (Nexus API)',
    targetLabel: 'Campaign Setting (Game)',
    startLabel: 'Open Grimoire',
    startSubLabel: 'Begin Scrying',
    protocolLabel: 'Astral Archive V.1492',
    cardBackLeft: 'Tome',
    cardBackRight: 'Fate',
  },
  [Game.RDR2]: {
    game: Game.RDR2,
    theme: 'rdr2',
    code: 'OMS',
    shortName: 'RDR2',
    name: 'Red Dead Redemption 2',
    primaryClass: 'text-[#d8b15e]',
    secondaryClass: 'text-[#c74435]',
    dangerClass: 'text-[#f05a42]',
    primaryBorderClass: 'border-[#d8b15e]',
    secondaryBorderClass: 'border-[#c74435]',
    primaryBgClass: 'bg-[#d8b15e]',
    secondaryBgClass: 'bg-[#c74435]',
    softPrimaryBgClass: 'bg-[#d8b15e]/10',
    softSecondaryBgClass: 'bg-[#c74435]/10',
    shadowClass: 'shadow-[0_24px_80px_rgba(199,68,53,0.13)]',
    frameClass: 'rounded-md border-[#6d3c22] bg-[#140c07]/90',
    panelClass: 'rounded-md border-2 border-[#6d3c22] bg-[#140c07]/92 backdrop-blur-sm',
    compactPanelClass: 'rounded-md border border-[#6d3c22] bg-[#140c07]/84',
    cardFrameClass: 'rounded-md border-2 border-[#6d3c22] bg-[#180e08] shadow-[0_26px_80px_rgba(0,0,0,0.58)]',
    previewFrameClass: 'rounded-md border border-[#d8b15e]/20 bg-[#150d08]/72 shadow-[0_18px_60px_rgba(216,177,94,0.1)]',
    cardBodyClass: 'bg-[linear-gradient(180deg,#231309,#110905)]',
    cardBackClass: 'rounded-md border-[#d8b15e]/36 bg-[linear-gradient(145deg,#2b1609,#120a06_48%,#1a0d06)] shadow-[0_20px_70px_rgba(216,177,94,0.12)]',
    buttonShapeClass: 'rounded-md',
    neutralButtonClass: 'rounded-md border-[#6d3c22] bg-[#120a06]/78 text-[#a77a4a] hover:border-[#d8b15e]/70 hover:text-[#d8b15e]',
    rejectButtonClass: 'rounded-md border-[#8b2f27]/60 bg-[#1a0907]/80 text-[#f05a42] hover:border-[#f05a42] hover:bg-[#f05a42]/10 hover:text-[#ffd4c8]',
    approveButtonClass: 'rounded-md border-[#d8b15e]/45 bg-[#160e08]/80 text-[#d8b15e] hover:border-[#d8b15e] hover:bg-[#d8b15e]/10 hover:text-white',
    landingPanelClass: 'rounded-md border-2 border-[#6d3c22] bg-[#120b07]/94 shadow-[0_24px_90px_rgba(0,0,0,0.58)]',
    landingAccentClass: 'before:absolute before:inset-x-0 before:top-0 before:h-2 before:bg-[repeating-linear-gradient(90deg,#6d3c22_0_20px,#d8b15e_20px_22px,#6d3c22_22px_42px)]',
    landingBackdropClass: 'bg-[radial-gradient(circle_at_top,rgba(199,68,53,0.2),transparent_34%),linear-gradient(180deg,#150906,#2a1209_54%,#070403)]',
    inputClass: 'bg-[#1b1009] border-[#6d3c22] focus:border-[#d8b15e]',
    listItemClass: 'border-[#6d3c22] bg-[#170d08]/72 hover:border-[#d8b15e]',
    progressGradientClass: 'from-[#d8b15e] via-[#c74435] to-[#3c1f14]',
    scanGridClass: 'rdr-boot-grid',
    titleClass: 'font-serif uppercase tracking-[0.04em]',
    bodyFontClass: 'font-serif',
    headerStatus: 'CAMP_LEDGER: OPEN',
    bootSystem: 'Camp Ledger Office',
    bootTitle: 'Dealing the Ledger',
    bootDescription: 'Pulling fresh mod notices from the Nexus telegraph and pinning the day’s choices to the camp board.',
    bootProgressLabel: 'Ledger Run',
    bootStatusFallback: 'Waiting on the telegraph...',
    bootThroughputFallback: 'No dispatch counted yet',
    phaseLabels: {
      auth: 'Badge Check',
      pool: 'Reading Wanted Posters',
      fetching: 'Collecting Dispatches',
      lists: 'Checking Station Boards',
      complete: 'Ledger Filed',
    },
    currentState: 'Riding',
    completeState: 'Stamped',
    waitingState: 'Hitched',
    introLabel: 'CARDS DEALT',
    previewState: 'Holstered',
    nextLabel: 'Next Notice',
    readyLabel: 'ready',
    recallLabel: 'BACKTRACKED',
    loadingTitle: 'Dealing the Ledger',
    loadingBody: 'Gathering mod notices from the Nexus telegraph.',
    loadingSubtext: 'The clerk is still sorting the pile.',
    emptyTitle: 'Board Cleared',
    emptyBody: 'Every notice in this batch has been judged.',
    emptySubtext: 'Refresh to ride another route.',
    approveLabel: 'Take',
    rejectLabel: 'Leave',
    approveOverlayLabel: 'Take',
    rejectOverlayLabel: 'Leave',
    approvedListTitle: 'CAMP_MOD_LEDGER',
    emptyApprovedText: 'NO MODS PINNED TO THE BOARD.',
    queueLabel: 'notices left',
    introStatus: 'dealing notices...',
    refreshStatus: 'checking telegraph...',
    refreshTitle: 'Telegraph Refresh',
    refreshBody: 'Checking new notices from Nexus.',
    resetTitle: 'Tear Up Ledger',
    resetAction: 'Tear It Up',
    exportLabel: 'Export Ledger',
    accessLabel: 'Telegraph Key (Nexus API)',
    targetLabel: 'Frontier (Game)',
    startLabel: 'Ride Out',
    startSubLabel: 'Open Ledger',
    protocolLabel: 'Camp Telegraph 1899',
    cardBackLeft: 'Ledger',
    cardBackRight: 'Camp',
  },
  [Game.STARDEW]: {
    game: Game.STARDEW,
    theme: 'stardew',
    code: 'SVS',
    shortName: 'Stardew',
    name: 'Stardew Valley',
    primaryClass: 'text-[#f2b84b]',
    secondaryClass: 'text-[#79c96b]',
    dangerClass: 'text-[#d96b59]',
    primaryBorderClass: 'border-[#f2b84b]',
    secondaryBorderClass: 'border-[#79c96b]',
    primaryBgClass: 'bg-[#f2b84b]',
    secondaryBgClass: 'bg-[#79c96b]',
    softPrimaryBgClass: 'bg-[#f2b84b]/12',
    softSecondaryBgClass: 'bg-[#79c96b]/12',
    shadowClass: 'shadow-[0_24px_70px_rgba(121,201,107,0.13)]',
    frameClass: 'rounded-xl border-[#8b5f35] bg-[#2f2113]/90',
    panelClass: 'rounded-xl border-2 border-[#8b5f35] bg-[#2f2113]/92 backdrop-blur-sm',
    compactPanelClass: 'rounded-xl border border-[#8b5f35] bg-[#2f2113]/84',
    cardFrameClass: 'rounded-xl border-2 border-[#8b5f35] bg-[#332316] shadow-[0_24px_70px_rgba(39,27,16,0.55)]',
    previewFrameClass: 'rounded-xl border border-[#79c96b]/25 bg-[#2f2113]/72 shadow-[0_18px_60px_rgba(121,201,107,0.12)]',
    cardBodyClass: 'bg-[linear-gradient(180deg,#3b2818,#25180f)]',
    cardBackClass: 'rounded-xl border-[#f2b84b]/40 bg-[linear-gradient(145deg,#4a321c,#2b1c11_50%,#372417)] shadow-[0_20px_60px_rgba(242,184,75,0.13)]',
    buttonShapeClass: 'rounded-xl',
    neutralButtonClass: 'rounded-xl border-[#8b5f35] bg-[#2f2113]/78 text-[#d9a96f] hover:border-[#f2b84b] hover:text-[#f2b84b]',
    rejectButtonClass: 'rounded-xl border-[#d96b59]/45 bg-[#382016]/80 text-[#e78975] hover:border-[#d96b59] hover:bg-[#d96b59]/10 hover:text-white',
    approveButtonClass: 'rounded-xl border-[#79c96b]/55 bg-[#1f2d18]/80 text-[#9ee08d] hover:border-[#79c96b] hover:bg-[#79c96b]/12 hover:text-white',
    landingPanelClass: 'rounded-xl border-2 border-[#8b5f35] bg-[#2f2113]/94 shadow-[0_24px_80px_rgba(47,33,19,0.5)]',
    landingAccentClass: 'before:absolute before:inset-x-6 before:top-4 before:h-2 before:rounded-full before:bg-[linear-gradient(90deg,#79c96b,#f2b84b,#7fc8e8)]',
    landingBackdropClass: 'bg-[radial-gradient(circle_at_top,rgba(127,200,232,0.16),transparent_36%),radial-gradient(circle_at_bottom,rgba(121,201,107,0.2),transparent_34%),linear-gradient(180deg,#20391f,#4a311d_64%,#1c140c)]',
    inputClass: 'bg-[#25180f] border-[#8b5f35] focus:border-[#79c96b]',
    listItemClass: 'border-[#8b5f35] bg-[#332316]/72 hover:border-[#79c96b]',
    progressGradientClass: 'from-[#79c96b] via-[#f2b84b] to-[#7fc8e8]',
    scanGridClass: 'sdv-boot-grid',
    titleClass: 'normal-case tracking-normal',
    bodyFontClass: 'font-sans',
    headerStatus: 'FARM_BOARD: SUNNY',
    bootSystem: 'Community Center Bulletin',
    bootTitle: 'Sorting the Basket',
    bootDescription: 'Checking Nexus bundles, arranging a fresh basket of mods, and pinning your favorites to the farm board.',
    bootProgressLabel: 'Harvest Run',
    bootStatusFallback: 'Waiting for the morning mail...',
    bootThroughputFallback: 'No parcels sorted yet',
    phaseLabels: {
      auth: 'Mailbox Check',
      pool: 'Walking the Notice Board',
      fetching: 'Gathering Parcels',
      lists: 'Checking Shop Catalogs',
      complete: 'Basket Packed',
    },
    currentState: 'Growing',
    completeState: 'Stored',
    waitingState: 'Seeded',
    introLabel: 'BASKET FILLING',
    previewState: 'Sprouting',
    nextLabel: 'Next Parcel',
    readyLabel: 'ripe',
    recallLabel: 'PICKED BACK UP',
    loadingTitle: 'Sorting the Basket',
    loadingBody: 'Gathering fresh mod parcels from the Nexus notice board.',
    loadingSubtext: 'Give the basket another moment.',
    emptyTitle: 'Basket Empty',
    emptyBody: 'Every parcel in this harvest has been sorted.',
    emptySubtext: 'Refresh to check the board again.',
    approveLabel: 'Plant',
    rejectLabel: 'Compost',
    approveOverlayLabel: 'Plant',
    rejectOverlayLabel: 'Compost',
    approvedListTitle: 'FARM_MOD_BASKET',
    emptyApprovedText: 'NO SEEDS SAVED FOR THE FARM.',
    queueLabel: 'parcels left',
    introStatus: 'filling basket...',
    refreshStatus: 'checking board...',
    refreshTitle: 'Market Refresh',
    refreshBody: 'Checking fresh parcels from Nexus.',
    resetTitle: 'Empty Basket',
    resetAction: 'Empty All',
    exportLabel: 'Export Basket',
    accessLabel: 'Mailbox Key (Nexus API)',
    targetLabel: 'Farm Plot (Game)',
    startLabel: 'Start Harvest',
    startSubLabel: 'Check Mail',
    protocolLabel: 'Community Board Year 1',
    cardBackLeft: 'Basket',
    cardBackRight: 'Farm',
  },
};

export const SUPPORTED_GAMES: Game[] = [
  Game.CYBERPUNK,
  Game.NEWVEGAS,
  Game.BG3,
  Game.RDR2,
  Game.STARDEW,
];

export const getGamePresentation = (game: Game): GamePresentation => presentations[game] ?? presentations[Game.CYBERPUNK];

export const isTheme = (game: Game, theme: ThemeId) => getGamePresentation(game).theme === theme;
